[package]
name = "pctan"
version = "0.1.0"
authors = ["lcagustini <torresmon235@gmail.com>"]
edition = "2018"

[dependencies]
rand = "*"

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2"
default-features = false
features = ["image", "ttf"]
